name: SigV4 Swift Tests

on:
  push:
    branches:
      - master
    paths:
      - sigv4-signing/swift/**
      - .github/workflows/sigv4-swift.yaml
  pull_request:
    branches:
      - master
    paths:
      - sigv4-signing/swift/**
      - .github/workflows/sigv4-swift.yaml

jobs:
  run-unit-tests:
    strategy:
      matrix:
        config:
          # x86_64
          - mac_ver: '15-intel'
            xc_ver: '16.4'
            test_results: true
          - mac_ver: '15-intel'
            xc_ver: '26.1.1'
          # arm64
          - mac_ver: '15'
            xc_ver: '16.4'
          - mac_ver: '15'
            xc_ver: '26.1.1'
      fail-fast: false

    name: 'Build and run unit tests (MacOS ${{ matrix.config.mac_ver }}, XCode ${{ matrix.config.xc_ver }})'
    runs-on: 'macos-${{ matrix.config.mac_ver }}'
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v4
      - name: Setup - Xcode
        run: >-
          sudo xcode-select -s /Applications/Xcode_${{ matrix.config.xc_ver }}.app
      - name: Install dependencies
        run: |
          cd sigv4-signing/swift/sigv4
          pod setup
          pod install --repo-update
      - name: XCode Test
        run: set -o pipefail && xcodebuild clean test -workspace sigv4-signing/swift/sigv4/sigv4.xcworkspace -scheme sigv4 -resultBundlePath TestResults -enableCodeCoverage YES | xcpretty
      - name: Publish results
        uses: slidoapp/xcresulttool@v3.1.0
        with:
          title: 'Test results (MacOS ${{ matrix.config.mac_ver }}, XCode ${{ matrix.config.xc_ver }})'
          path: TestResults.xcresult
          upload-bundles: never
        if: ${{ (success() || failure()) && matrix.config.test_results == true }}
